language: node_js
node_js:
- node
- '12'
- '10'
- '8'
install:
- yarn install
script:
- yarn run ci-test
deploy:
  provider: npm
  email: jonathan.griggs@gmail.com
  api_key:
    secure: WhiPPhT4MbiEKQDkh46txbqm+zUpUo8Rnk2HRGd1ksfpa0k62xM9nFGeS76nBgR/9nKvhCGyXydW3P0P0j6wAFCm3dK/m+AqvHF8HHGic8VO8nRU3WFLdhiM/7Op0gOQub9cFYwBcShQ/p/uPbxpXg8h258jhFC/oHFsWoJNR5XzIdlBZNNCvbRweZxQDUTrG+m3RJrnOeM+Q0xd7hPh8pgBGOJIscV8J2pUg8q512UyPOc3CIex/hUYRm+XKdLf8xlBxobUGnS8ksp3N8JzJJpi9si/4EQqOHPqxk9kendbW3ETqvE4Cm45vvXxOgbDhRkGTwkAvRUdt0sEWRXAzWoFO4RSm4N5ZQfGX7HKaDkPU4a+cl1eZMoaGvTW4pXexKjiSqakNggs+7BD2oOz4edp0LA+vvYH8hMTfVSOSzNRguaTwVgiFGxUu04JTo9KAwzzU+UFfaOnRZ8empz1nK4Qh9p3kh1kRr0EEiRicX54vfZOBO4O8mWwW2LrQnsjUghYLYgTAKi8s90bNCpTaycNhXlB7r751mtkezuVOUtqMO9YUCE33qTc+9jeb6yNGsi7+AoUO3dnoFmO9JS3297yVhnoNnpRaR+qGXJnW27zkfSK1+nhB1sBoH8d22fMua7+Toxx+hatnLqrOi1zyFomqdxzi7a8EUDp6IKy/EU=
  on:
    tags: true
    repo: growombud/prolly
    branch: master
